# this docker-compose.yml runs on Digital Ocean
version: '3.1'

services:
  ##########
  # APACHE #
  ##########
  apache:
    build:
      context: ./
      dockerfile: ./docker/apache/Dockerfile
    volumes:
      - apache_certs: /usr/local/apache2/md
    ports:
    - 80:80
    - 443:443
    environment:
      APACHE_DOMAIN: ${APACHE_DOMAIN}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      APACHE_LOG_DIR: /usr/local/apache2/logs
  ############
  # DATABASE #
  ############
  database:
    build:
      context: ./
      dockerfile: ./docker/database/Dockerfile
    volumes:
      - db_data:/postgres-data
    ports:
      - ${DC_POSTGRES_PORT}:5432
    environment:
      # See Dockerfile for details
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  ###########
  # ADMINER #
  ###########
  adminer:
    build:
      context: ./
      dockerfile: ./docker/adminer/Dockerfile
    depends_on:
      - database
    ports:
      - ${DC_ADMINER_PORT}:8080
    environment:
      # See Dockerfile for details
      ADMINER_DB_SERVER: ${DB_HOST}
      ADMINER_DB_NAME: ${DB_NAME}
      ADMINER_DB_USER: ${DB_USER}
      ADMINER_DB_PASSWORD: ${DB_USER_PASSWORD}
volumes:
  db_data:
  apache_certs:
