version: '3.1'

services:
  # backend:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/backend/Dockerfile
  # frontend:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/frontend/Dockerfile
  database:
    build:
      context: ./
      dockerfile: ./docker/database/Dockerfile
    volumes: 
      - db_data:/postgres-data
    ports:
      - ${DC_POSTGRES_PORT}:5432
    environment:
      # See Dockerfile for details
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  adminer:
    build:
      context: ./
      dockerfile: ./docker/adminer/Dockerfile
    depends_on:
      - database
    ports:
      - ${DC_ADMINER_PORT}:8080
    environment:
      # See Dockerfile for details
      ADMINER_AUTOLOGIN: 'true'
      ADMINER_DB_SERVER: ${DB_HOST}
      ADMINER_DB_NAME: ${DB_NAME}
      ADMINER_DB_USER: ${DB_USER}
      ADMINER_DB_PASSWORD: ${DB_USER_PASSWORD}
volumes:
  db_data:
