# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Create .env file
      - name: Create .env file
        run: |
          cat <<END_OF_HEREDOC > .env
          DC_BACKEND_TOMCAT_PORT=${{ secrets.DC_BACKEND_TOMCAT_PORT }}
          DC_BACKEND_DEBUG_PORT=${{ secrets.DC_BACKEND_DEBUG_PORT }}
          DC_PYTHON_PORT=7000=${{ secrets.DC_PYTHON_PORT }}
          DC_FRONTEND_PORT=${{ secrets.DC_FRONTEND_PORT }}
          DC_POSTGRES_PORT=${{ secrets.DC_POSTGRES_PORT }}
          DC_ADMINER_PORT=${{ secrets.DC_ADMINER_PORT }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_USER_PASSWORD=${{ secrets.DB_USER_PASSWORD }}
          APACHE_DOMAIN=${{ secrets.APACHE_DOMAIN }}
          ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}
          APACHE_LOG_DIR=${{ secrets.APACHE_LOG_DIR }}
          END_OF_HEREDOC

      # Build and run docker containers
      - name: Build and run docker containers
        run: docker-compose --file deploy.docker-compose.yml up --build --detach
